import React, { useMemo } from 'react';
import { renderChartSvg, resolveChartSpec, parseChartBlock } from '@ai-studio/format/browser';

/**
 * Render a chart spec as inline SVG.
 *
 * The SVG comes from the same renderer the digest and the exporter use, so what is
 * on screen, what lands in `AI.md`, and what a .pptx contains all describe the
 * same chart. It is injected as markup rather than built as React elements because
 * the renderer is shared with non-React callers; the string is generated by our own
 * code and every text node is escaped inside it.
 */
export default function ChartView({ spec, md, sheet, width, height, surface = '#ffffff' }) {
  const svg = useMemo(() => {
    const source = spec ?? (md ? parseChartBlock(md) : null);
    if (!source) return null;
    const resolved = sheet ? resolveChartSpec(source, sheet) : source;
    return renderChartSvg(resolved, {
      width: Math.max(200, Math.round(width ?? 480)),
      height: Math.max(140, Math.round(height ?? 300)),
      surface,
    });
  }, [spec, md, sheet, width, height, surface]);

  if (!svg) {
    return (
      <div className="chart-broken">
        차트 정의를 읽을 수 없습니다. <code>```chart</code> 블록의 JSON을 확인하세요.
      </div>
    );
  }

  return <div className="chart-view" dangerouslySetInnerHTML={{ __html: svg }} />;
}
