import React, { useMemo, useState } from 'react';
import { writeSlide, writeSection, writeSheet, buildDigest, slugify } from '../core/index.js';
import { highlight } from '../lib/markdown.js';

const HINTS = {
  deck: (
    <>
      슬라이드마다 <code>.md</code>(내용)와 <code>.layout.json</code>(좌표·스타일) 한 쌍이 저장됩니다.
      편집하는 즉시 아래 내용이 그대로 디스크에 기록됩니다.
    </>
  ),
  doc: (
    <>
      문단 서식이 기본값이면 <code>.md</code>는 순수 마크다운으로 유지되고, 서식을 준 문단만{' '}
      <code>&lt;!-- block:id --&gt;</code> 앵커와 <code>.meta.json</code> 항목을 갖습니다.
    </>
  ),
  grid: (
    <>
      <code>.cells.json</code>이 계산의 원천이고 <code>.md</code>는 AI가 읽는 투영입니다. 표에는 계산된
      값이, 아래 <code>수식</code> 절에는 수식과 결과가 함께 들어갑니다.
    </>
  ),
};

/**
 * Live view of the files this project would write right now.
 *
 * It runs the very same serializers the server uses, so what the panel shows is
 * byte-identical to what lands on disk — the point being that the storage format
 * is not hidden behind the editor, it *is* the product.
 */
export default function FileInspector({ project, activeIndex, onClose }) {
  const [tab, setTab] = useState('md');

  const files = useMemo(() => buildFiles(project, activeIndex), [project, activeIndex]);
  const current = files.find((f) => f.key === tab) ?? files[0];

  return (
    <aside className="panel panel--right panel--wide">
      <div className="panel__head">
        <span>AI 저장 포맷</span>
        {onClose && (
          <button className="panel__close" onClick={onClose} title="패널 닫기" aria-label="패널 닫기">
            ✕
          </button>
        )}
      </div>
      <div className="inspector__tabs" role="tablist" aria-label="파일">
        {files.map((f) => (
          <button
            key={f.key}
            role="tab"
            className="inspector__tab"
            aria-selected={f.key === current?.key}
            onClick={() => setTab(f.key)}
            title={f.name}
          >
            {f.name}
          </button>
        ))}
      </div>
      <p className="hint">{HINTS[project.type]}</p>
      <div className="panel__body">
        <pre
          className="code"
          // The content is generated by our own serializers and escaped by
          // `highlight`; nothing user-supplied reaches the DOM unescaped.
          dangerouslySetInnerHTML={{ __html: highlight(current?.content ?? '', current?.lang) }}
        />
      </div>
    </aside>
  );
}

function buildFiles(project, activeIndex) {
  const files = [];
  try {
    // One serializer, shared with the save path: the `json` these return is the
    // formatted text that will be on disk, not an object to re-encode here.
    const pair = ({ item, name, write, suffix }) => {
      if (!item) return;
      const { md, json } = write(item);
      const stem = `${pad(activeIndex + 1)}-${slugify(name)}`;
      files.push({ key: 'md', name: `${stem}.md`, content: md, lang: 'md' });
      files.push({ key: 'json', name: `${stem}${suffix}`, content: json, lang: 'json' });
    };

    if (project.type === 'deck') {
      const slide = project.slides?.[activeIndex];
      pair({
        item: slide,
        name: slide?.title || '슬라이드',
        write: writeSlide,
        suffix: '.layout.json',
      });
    } else if (project.type === 'doc') {
      const section = project.sections?.[activeIndex];
      pair({
        item: section,
        name: section?.name || '섹션',
        write: writeSection,
        suffix: '.meta.json',
      });
    } else {
      const sheet = project.sheets?.[activeIndex];
      pair({
        item: sheet,
        name: sheet?.name || '시트',
        write: writeSheet,
        suffix: '.cells.json',
      });
    }

    files.push({ key: 'digest', name: 'AI.md', content: buildDigest(project), lang: 'md' });
    files.push({
      key: 'manifest',
      name: 'manifest.json',
      content: pretty(project.manifest),
      lang: 'json',
    });
  } catch (error) {
    files.push({
      key: 'error',
      name: '오류',
      content: `직렬화 중 오류가 발생했습니다:\n${error.message}`,
      lang: 'md',
    });
  }
  return files;
}

const pad = (n) => String(n).padStart(2, '0');
const pretty = (value) => `${JSON.stringify(value, null, 2)}\n`;
