[package]
name = "ai-studio-app"
description = "AI Studio desktop app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "ai-studio"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ai-core = { workspace = true }
ai-format = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { version = "2" }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
directories = "5"
